export const SP_CITIES = Array.from(new Set([
  "São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "São José dos Campos", 
  "Osasco", "Ribeirão Preto", "Sorocaba", "Mauá", "São José do Rio Preto", "Mogi das Cruzes", 
  "Santos", "Diadema", "Jundiaí", "Piracicaba", "Carapicuíba", "Bauru", "Itaquaquecetuba", 
  "São Vicente", "Franca", "Guarujá", "Praia Grande", "Taubaté", "Limeira", "Suzano", 
  "Taboão da Serra", "Sumaré", "Barueri", "Embu das Artes", "Indaiatuba", "Cotia", 
  "Americana", "Itu", "Itapevi", "Araraquara", "Hortolândia", "Jacareí", "Presidente Prudente", 
  "Marília", "Rio Claro", "Itapecom", "Bragança Paulista", "Itatiba", "Sertãozinho", 
  "Ferraz de Vasconcelos", "Valinhos", "Araras", "Cruzeiro", "Atibaia", "Botucatu", "Araçatuba",
  "Pindamonhangaba", "Avaré", "Assis", "Adamantina", "Aguaí", "Águas de Lindoia", "Águas de Santa Bárbara",
  "Águas de São Pedro", "Agudos", "Alambari", "Alfredo Marcondes", "Altinópolis", "Alto Alegre",
  "Alumínio", "Álvaro de Carvalho", "Álvares Florence", "Álvares Machado",
  "Américo Brasiliense", "Américo de Campos", "Amparo", "Analândia", "Andradina", "Angatuba",
  "Anhembi", "Anhumas", "Aparecida", "Aparecida d'Oeste", "Apiaí", "Araçariguama",
  "Arco-Íris", "Arealva", "Areias", "Areiópolis", "Ariranha", "Artur Nogueira",
  "Arujá", "Aspásia", "Auriflama", "Avaí", "Avanhandava",
  "Bady Bassitt", "Balbinos", "Bálsamo", "Bananal", "Barão de Antonina", "Barbosa",
  "Bariri", "Barra Bonita", "Barra do Chapéu", "Barra do Turvo", "Barretos", "Barrinha",
  "Bastos", "Batatais", "Bebedouro", "Bento de Abreu", "Bernardino de Campos",
  "Bertioga", "Bilac", "Birigui", "Biritiba-Mirim", "Boa Esperança do Sul", "Bocaina",
  "Bofete", "Boituva", "Bom Jesus dos Perdões", "Bom Sucesso de Itararé", "Borá", "Boraceia",
  "Borborema", "Borebi", "Braúna", "Brejo Alegre", "Brodowski",
  "Brotas", "Buri", "Buritama", "Buritizal", "Cabrália Paulista", "Cabreúva", "Caçapava",
  "Cachoeira Paulista", "Caconde", "Cafelândia", "Caiabu", "Caieiras", "Caiuá", "Cajamar",
  "Cajati", "Cajobi", "Cajuru", "Campina do Monte Alegre", "Campo Limpo Paulista",
  "Campos do Jordão", "Campos Novos Paulista", "Cananeia", "Canas", "Cândido Mota",
  "Cândido Rodrigues", "Canitar", "Capão Bonito", "Capela do Alto", "Capivari", "Caraguatatuba",
  "Cardoso", "Casa Branca", "Cássia dos Coqueiros", "Castilho", "Catanduva",
  "Catiguá", "Catobi", "Cerqueira César", "Cerquilho", "Cesário Lange", "Charqueada",
  "Chavantes", "Clementina", "Colina", "Colômbia", "Conchal", "Conchas", "Cordeirópolis",
  "Coroados", "Coronel Macedo", "Corumbataí", "Cosmópolis", "Cosmorama",
  "Cristais Paulista", "Cruzália", "Cubatão", "Cunha", "Descalvado",
  "Dirce Reis", "Divinolândia", "Dobrada", "Dois Córregos", "Dolcinópolis", "Dourado",
  "Dracena", "Duartina", "Dumont", "Echaporã", "Eldorado", "Elias Fausto", "Elisiário",
  "Embu-Guaçu", "Emilianópolis", "Engenheiro Coelho", "Espírito Santo do Pinhal",
  "Espírito Santo do Turvo", "Estrela d'Oeste", "Estrela do Norte", "Euclides da Cunha Paulista",
  "Fartura", "Fernandópolis", "Fernando Prestes", "Fernão",
  "Flora Rica", "Floreal", "Flórida Paulista", "Florínia", "Francisco Morato",
  "Franco da Rocha", "Gabriel Monteiro", "Gália", "Garça", "Gastão Vidigal", "Gavião Peixoto",
  "General Salgado", "Getulina", "Glicério", "Guaiçara", "Guaimbê", "Guaíra", "Guapiaçu",
  "Guapiara", "Guará", "Guaraçaí", "Guaraci", "Guarani d'Oeste", "Guarantã", "Guararapes",
  "Guararema", "Guaratinguetá", "Guareí", "Guariba", "Guatapará",
  "Guzolândia", "Herculândia", "Holambra", "Iacanga", "Iacri", "Iaras",
  "Ibaté", "Ibirá", "Ibirarema", "Ibitinga", "Ibiúna", "Icém", "Iepê", "Igaraçu do Tietê",
  "Igarapava", "Igaratá", "Igorapava", "Ilha Comprida", "Ilha Solteira", "Ilhabela",
  "Indiana", "Indiaporã", "Inúbia Paulista", "Ipauçu", "Iperó", "Ipeúna",
  "Ipiguá", "Iporanga", "Ipuã", "Iracemápolis", "Irapuã", "Irapuru", "Itaberá", "Itaí",
  "Itajobi", "Itaju", "Itanhaém", "Itapecerica da Serra", "Itapetininga", "Itapeva",
  "Itapira", "Itapirapuã Paulista", "Itápolis", "Itaporanga", "Itapuí",
  "Itapura", "Itararé", "Itariri", "Itatinga", "Itirapina",
  "Itirapuã", "Itobi", "Itupeva", "Ituverava", "Jaborandi", "Jaboticabal",
  "Jaci", "Jacupiranga", "Jaguariúna", "Jales", "Jambeiro", "Jandira", "Jardinópolis",
  "Jarinu", "Jaú", "Jeriquara", "Joanópolis", "João Ramalho", "José Bonifácio", "Júlio Mesquita",
  "Jumirim", "Junqueirópolis", "Juquiá", "Juquitiba", "Lagoinha", "Laranjal Paulista",
  "Lavínia", "Lavrinhas", "Leme", "Lençóis Paulista", "Lindóia", "Lins", "Lorena",
  "Lourdes", "Louveira", "Lucélia", "Lucianópolis", "Luís Antônio", "Luiziânia", "Lupércio",
  "Lutécia", "Macatuba", "Macaubal", "Macedônia", "Magda", "Mairinque", "Mairiporã", "Manduri",
  "Marabá Paulista", "Maracaí", "Marapoama", "Mariápolis", "Marinópolis", "Martinópolis",
  "Matão", "Mendonça", "Meridiano", "Mesópolis", "Miguelópolis", "Mineiros do Tietê",
  "Mira Estrela", "Miracatu", "Mirandópolis", "Mirante do Paranapanema", "Mirassol", "Mirassolândia",
  "Mococa", "Mogi Guaçu", "Mogi Mirim", "Mombuca", "Monções", "Mongaguá",
  "Monte Alegre do Sul", "Monte Alto", "Monte Aprazível", "Monte Azul Paulista", "Monte Castelo",
  "Monte Mor", "Monteiro Lobato", "Monterópolis", "Morro Agudo", "Morungaba", "Motuca",
  "Murutinga do Sul", "Nantes", "Narandiba", "Natividade da Serra", "Nazaré Paulista",
  "Neves Paulista", "Nhandeara", "Nipoã", "Nova Aliança", "Nova Campina", "Nova Canaã Paulista",
  "Nova Castilho", "Nova Europa", "Nova Granada", "Nova Guataporanga", "Nova Independência",
  "Nova Luzitânia", "Nova Odessa", "Novais", "Novo Horizonte", "Nuporanga", "Ocauçu", "Óleo",
  "Olímpia", "Onda Verde", "Oriente", "Orindiúva", "Orlândia", "Oscar Bressane",
  "Osvaldo Cruz", "Ourinhos", "Ouro Verde", "Ouroeste", "Pacaembu", "Palestina", "Palmares Paulista",
  "Palmeira d'Oeste", "Palmital", "Panorama", "Paraguaçu Paulista", "Paraibuna", "Paraíso",
  "Paranapanema", "Paranapuã", "Parapuã", "Pardinho", "Pariquera-Açu", "Parisi", "Patrocínio Paulista",
  "Paulicéia", "Paulínia", "Paulistânia", "Paulo de Faria", "Pederneiras", "Pedra Bela",
  "Pedranópolis", "Pedregulho", "Pedreira", "Pedrinhas Paulista", "Pedro de Toledo", "Penápolis",
  "Pereira Barreto", "Pereiras", "Peruíbe", "Piacatu", "Piedade", "Pilar do Sul",
  "Pindorama", "Pinhalzinho", "Piquerobi", "Piquete", "Piracaia", "Piraju",
  "Pirajuí", "Pirangi", "Pirapora do Bom Jesus", "Pirapozinho", "Pirassununga", "Piratininga",
  "Pitangueiras", "Planalto", "Platina", "Poá", "Poloni", "Pompeia", "Pongaí", "Pontal",
  "Pontalinda", "Pontes Gestal", "Populina", "Porangaba", "Porto Feliz", "Porto Ferreira",
  "Potim", "Potirendaba", "Pracinha", "Pradópolis", "Pratânia", "Presidente Alves",
  "Presidente Bernardes", "Presidente Epitácio", "Presidente Venceslau",
  "Promissão", "Quatá", "Queiroz", "Queluz", "Quintana", "Rafard", "Rancharia", "Redenção da Serra",
  "Regente Feijó", "Reginópolis", "Registro", "Restinga", "Ribeira", "Ribeirão Bonito",
  "Ribeirão Branco", "Ribeirão Corrente", "Ribeirão do Sul", "Ribeirão dos Índios",
  "Ribeirão Grande", "Ribeirão Pires", "Riversul", "Riolândia", "Rifaina",
  "Rinópolis", "Rio das Pedras", "Rio Grande da Serra", "Rosana", "Roseira",
  "Rubiácea", "Rubinéia", "Sabino", "Sagres", "Sales", "Sales Oliveira", "Salesópolis",
  "Salmourão", "Saltinho", "Salto", "Salto de Pirapora", "Salto Grande", "Sandovalina",
  "Santa Adélia", "Santa Albertina", "Santa Bárbara d'Oeste", "Santa Branca", "Santa Clara d'Oeste",
  "Santa Cruz da Conceição", "Santa Cruz da Esperança", "Santa Cruz das Palmeiras",
  "Santa Cruz do Rio Pardo", "Santa Ernestina", "Santa Fé do Sul", "Santa Gertrudes",
  "Santa Isabel", "Santa Lúcia", "Santa Maria da Serra", "Santa Mercedes", "Santa Rita d'Oeste",
  "Santa Rita do Passa Quatro", "Santa Rosa de Viterbo", "Santa Salete", "Santana da Ponte Pensa",
  "Santana de Parnaíba", "Santo Anastácio", "Santo Antônio da Alegria",
  "Santo Antônio de Posse", "Santo Antônio do Aracanguá", "Santo Antônio do Jardim",
  "Santo Antônio do Pinhal", "Santo Expedito", "Santópolis do Aguapeí",
  "São Bento do Sapucaí", "São Caetano do Sul", "São Carlos",
  "São Francisco", "São João da Boa Vista", "São João das Duas Pontes", "São João de Iracema",
  "São João do Pau-d'Alho", "São Joaquim da Barra", "São José da Bela Vista", "São José do Barreiro",
  "São José do Rio Pardo", "São Lourenço da Serra",
  "São Luiz do Paraitinga", "São Manuel", "São Miguel Arcanjo", "São Pedro",
  "São Pedro do Turvo", "São Roque", "São Sebastião", "São Sebastião da Grama",
  "Sarapuí", "Sarutaiá", "Sebastianópolis do Sul", "Serra Azul", "Serra Negra", "Serrana",
  "Sete Barras", "Severínia", "Silveiras", "Socorro", "Sud Mennucci",
  "Suzanápolis", "Tabapuã", "Tabatinga", "Taciba",
  "Taguaí", "Taiaçu", "Taiúva", "Tambaú", "Tanabi", "Tapiraí", "Tapiratiba", "Taquaral",
  "Taquaritinga", "Taquarituba", "Taquarivaí", "Tarabai", "Tarumã", "Tatuí",
  "Tejupá", "Teodoro Sampaio", "Terra Roxa", "Tietê", "Timburi", "Torre de Pedra", "Torrinha",
  "Trabiju", "Tremembé", "Três Fronteiras", "Tuiuti", "Tupã", "Tupi Paulista", "Turiúba",
  "Turmalina", "Ubarana", "Ubatuba", "Ubirajara", "Uchoa", "União Paulista", "Urania",
  "Uru", "Urupês", "Valentim Gentil", "Valparaíso", "Vargem", "Vargem Grande do Sul",
  "Vargem Grande Paulista", "Várzea Paulista", "Vera Cruz", "Vinhedo", "Viradouro",
  "Vista Alegre do Alto", "Vitória Brasil", "Votorantim", "Votuporanga", "Zacarias"
])).sort();

export const BAIRROS_SJC = [
  "Jardim Aquarius", "Vila Adyana", "Urbanova", "Jardim das Colinas", 
  "Vila Ema", "Jardim Esplanada", "Bosque dos Eucaliptos", "Jardim Satélite", 
  "Parque Industrial", "Vila Industrial", "Jardim Alvorada", "Jardim América"
].sort();

export const BAIRROS_SP = [
  "Pinheiros", "Vila Madalena", "Itaim Bibi", "Moema", "Jardins", 
  "Vila Mariana", "Brooklin", "Campo Belo", "Perdizes", "Higienópolis", 
  "Tatuapé", "Santana", "Consolação", "Bela Vista", "Vila Olímpia"
].sort();
